_wandb:
    value:
        cli_version: 0.21.1
        e:
            x5mcpmo2vtk2msp7brts781v33k2mb0u:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                args:
                    - --train_csv
                    - data/train.csv
                    - --max_features
                    - "50000"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "199752531968"
                email: alexholyk@gmail.com
                executable: /Users/alexanderholyk/Documents/Study/_ML_Ops/comment_moderation/.venv/bin/python
                git:
                    commit: 462cd76ce057265789af8cec28b5c9c651e37c4d
                    remote: git@github.com:alexanderholyk/toxic_comment_moderation.git
                host: Alexanders-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.6-arm64-arm-64bit
                program: -m src.training.train
                python: CPython 3.12.7
                root: /Users/alexanderholyk/Documents/Study/_ML_Ops/comment_moderation
                startedAt: "2025-08-26T23:42:58.740686Z"
                writerId: x5mcpmo2vtk2msp7brts781v33k2mb0u
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
            "4": 3.12.7
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
labels:
    value:
        - toxic
        - severe_toxic
        - obscene
        - threat
        - insult
        - identity_hate
max_features:
    value: 50000
model_type:
    value: tfidf_logreg_ovr
