FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY monitoring_app ./monitoring_app
EXPOSE 8501
CMD ["streamlit", "run", "monitoring_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]