_wandb:
    value:
        cli_version: 0.21.1
        code_path: source-toxic-moderation-None
        e:
            4h5iajdfgqor5nhb6b14i76ehgqpq2xm:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                args:
                    - --train_csv
                    - data/train.csv
                    - --max_features
                    - "50000"
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "199729778688"
                email: alexholyk@gmail.com
                executable: /Users/alexanderholyk/Documents/Study/_ML_Ops/comment_moderation/.venv/bin/python
                git:
                    commit: f35016ee0c6f91b122be76a333436ca63b238f93
                    remote: git@github.com:alexanderholyk/toxic_comment_moderation.git
                host: Alexanders-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-15.6-arm64-arm-64bit
                program: -m src.training.train
                python: CPython 3.12.7
                root: /Users/alexanderholyk/Documents/Study/_ML_Ops/comment_moderation
                startedAt: "2025-08-27T00:08:57.515732Z"
                writerId: 4h5iajdfgqor5nhb6b14i76ehgqpq2xm
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.7
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
classifier:
    value:
        C: 1
        class_weight: balanced
        family: LogisticRegression
        max_iter: 1000
        penalty: l2
        solver: liblinear
        tol: 0.0001
data:
    value:
        sha256: bd4084611bd27c939ba98e5e63bc3e5a2c1a4e99477dcba46c829e4c986c429d
        train_csv: /Users/alexanderholyk/Documents/Study/_ML_Ops/comment_moderation/data/train.csv
git_sha:
    value: f35016e
labels:
    value:
        - toxic
        - severe_toxic
        - obscene
        - threat
        - insult
        - identity_hate
random_state:
    value: 42
test_size:
    value: 0.2
vectorizer:
    value:
        max_df: 0.9
        max_features: 50000
        min_df: 3
        ngram_range:
            - 1
            - 2
        sublinear_tf: true
