name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Optional dev/CI extras; ignore if not present
          pip install -r requirements-dev.txt || true
          pip install ruff==0.6.3

      - name: Ruff check
        run: ruff check --output-format=github .

  test:
    name: Tests (pytest)
    runs-on: ubuntu-latest
    env:
      # Make sure tests don't try to hit real external services
      WANDB_DISABLED: "true"
      DEV_DB_SKIP: "1"          # our API/db layer no-ops without a DB
      PYTHONPATH: "."
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Optional dev/CI extras; ignore if not present
          pip install -r requirements-dev.txt || true
          # If you have a pyproject with extras for testing, you could do:
          # pip install ".[test]" || true
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest -q